# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "zasm"
languages = ["CXX"]

[options]
ZASM_BUILD_TESTS = true
ZASM_BUILD_BENCHMARKS = true

[conditions]
tests = "ZASM_BUILD_TESTS"
benchmarks = "ZASM_BUILD_BENCHMARKS"

[subdir.thirdparty]

[target.zasm]
type = "static"
alias = "zasm::zasm"
sources = [
    "src/zasm/**.cpp",
    "include/zasm/**.hpp",
]
include-directories = ["include"]
compile-features = ["cxx_std_17"]
link-libraries = ["Zydis"]

[target.testing]
condition = "tests"
type = "executable"
sources = ["src/testing/testing.cpp"]
link-libraries = ["zasm::zasm"]

[target.testdata]
condition = "tests"
type = "interface"
alias = "zasm::testdata"
include-directories = ["src/testdata"]

[target.tests]
condition = "tests"
type = "executable"
msvc.compile-options = ["/bigobj"]
sources = [
    "src/tests/**.cpp",
    "src/tests/**.hpp",
]
link-libraries = [
    "zasm::zasm",
	"zasm::testdata",
    "GTest::gtest",
]

[target.benchmarks]
condition = "tests"
type = "executable"
msvc.compile-options = ["/bigobj"]
sources = [
    "src/benchmark/**.cpp",
    "src/benchmark/**.hpp",
]
link-libraries = [
    "zasm::zasm",
	"zasm::testdata",
    "benchmark::benchmark",
]

[[test]]
condition = "tests"
name = "tests"
command = "$<TARGET_FILE:tests>"
